import { extraCommandOptions } from "./command-options-extra.js";
import { systemCommandOptions } from "./command-options-system.js";
import { toolCommandOptions } from "./command-options-tools.js";

const option = (name, description, example) => ({ option: name, description, example });

export const commandOptions = {
  ls: [
    option("-a, --all", "显示所有项目，包括名称以点开头的隐藏文件。", "ls -a"),
    option("-A, --almost-all", "显示隐藏项目，但不显示 . 和 ..。", "ls -A"),
    option("--author", "与 -l 一起使用时显示每个文件的作者。", "ls -l --author"),
    option("-b, --escape", "用 C 风格转义序列显示不可打印字符。", "ls -b"),
    option("--block-size=SIZE", "按指定单位显示文件大小，例如 K、M、G。", "ls -l --block-size=M"),
    option("-B, --ignore-backups", "不显示名称以 ~ 结尾的备份文件。", "ls -B"),
    option("-c", "配合 -lt 按状态变更时间排序；配合 -l 显示状态变更时间。", "ls -ltc"),
    option("-C", "按列排列项目。", "ls -C"),
    option("--color[=WHEN]", "控制彩色输出，WHEN 可为 always、auto 或 never。", "ls --color=auto"),
    option("-d, --directory", "显示目录本身，而不是列出目录内容。", "ls -ld /var/log"),
    option("-D, --dired", "生成适合 Emacs dired 模式处理的输出。", "ls -lD"),
    option("-f", "不排序，同时启用 -aU 并禁用 -ls 和颜色。", "ls -f"),
    option("-F, --classify", "在项目末尾追加类型标识，例如 /、*、@。", "ls -F"),
    option("--file-type", "追加文件类型标识，但不为可执行文件追加 *。", "ls --file-type"),
    option("--format=WORD", "指定输出格式，如 long、commas、horizontal、vertical。", "ls --format=long"),
    option("--full-time", "使用完整 ISO 时间格式，等同于 -l --time-style=full-iso。", "ls --full-time"),
    option("-g", "类似 -l，但不显示文件所有者。", "ls -g"),
    option("--group-directories-first", "将目录排在普通文件之前。", "ls --group-directories-first"),
    option("-G, --no-group", "在长格式中不显示组名。", "ls -lG"),
    option("-h, --human-readable", "配合 -l 或 -s，以 K、M、G 等易读单位显示大小。", "ls -lh"),
    option("--si", "使用 1000 进制而不是 1024 进制显示易读大小。", "ls -l --si"),
    option("-H, --dereference-command-line", "跟随命令行参数中指定的符号链接。", "ls -lH link"),
    option("--dereference-command-line-symlink-to-dir", "跟随命令行中指向目录的符号链接。", "ls --dereference-command-line-symlink-to-dir link"),
    option("--hide=PATTERN", "隐藏匹配 Shell 模式的项目；-a 或 -A 会覆盖此选项。", "ls --hide='*.tmp'"),
    option("--hyperlink[=WHEN]", "为文件名生成终端超链接，WHEN 可为 always、auto、never。", "ls --hyperlink=auto"),
    option("--indicator-style=WORD", "按指定方式追加类型标识，如 none、slash、file-type、classify。", "ls --indicator-style=slash"),
    option("-i, --inode", "显示每个文件的 inode 编号。", "ls -i"),
    option("-I, --ignore=PATTERN", "不显示匹配指定 Shell 模式的项目。", "ls -I '*.log'"),
    option("-k, --kibibytes", "使用 1024 字节块，主要用于 -s 和目录汇总。", "ls -sk"),
    option("-l", "使用长格式显示权限、链接数、所有者、大小和时间。", "ls -l"),
    option("-L, --dereference", "显示符号链接指向对象的信息，而不是链接本身。", "ls -lL link"),
    option("-m", "用逗号分隔项目并填满每一行。", "ls -m"),
    option("-n, --numeric-uid-gid", "类似 -l，但显示数字 UID 和 GID。", "ls -ln"),
    option("-N, --literal", "原样显示文件名，不添加引号。", "ls -N"),
    option("-o", "类似 -l，但不显示组信息。", "ls -o"),
    option("-p, --indicator-style=slash", "在目录名称末尾追加 /。", "ls -p"),
    option("-q, --hide-control-chars", "将文件名中的不可打印字符显示为 ?。", "ls -q"),
    option("--show-control-chars", "原样显示文件名中的不可打印字符。", "ls --show-control-chars"),
    option("-Q, --quote-name", "用双引号包围文件名。", "ls -Q"),
    option("--quoting-style=WORD", "指定文件名引用风格，如 literal、shell、c、escape。", "ls --quoting-style=shell"),
    option("-r, --reverse", "反转当前排序结果。", "ls -lr"),
    option("-R, --recursive", "递归列出所有子目录。", "ls -R"),
    option("-s, --size", "显示每个文件分配的磁盘块数。", "ls -s"),
    option("-S", "按文件大小降序排列。", "ls -lS"),
    option("--sort=WORD", "指定排序字段，如 none、size、time、version、extension。", "ls --sort=size"),
    option("--time=WORD", "指定显示或排序使用的时间，如 atime、access、ctime、status。", "ls -l --time=atime"),
    option("--time-style=TIME_STYLE", "指定长格式时间样式，如 full-iso、long-iso、iso 或自定义格式。", "ls -l --time-style=long-iso"),
    option("-t", "按修改时间降序排列。", "ls -lt"),
    option("-T, --tabsize=COLS", "设置制表符宽度。", "ls -T 4"),
    option("-u", "配合 -lt 按访问时间排序；配合 -l 显示访问时间。", "ls -ltu"),
    option("-U", "不排序，按目录中的存储顺序显示。", "ls -U"),
    option("-v", "按文本中的版本号进行自然排序。", "ls -v"),
    option("-w, --width=COLS", "设置输出宽度；0 表示不限制。", "ls -w 120"),
    option("-x", "按行而不是按列排列项目。", "ls -x"),
    option("-X", "按文件扩展名排序。", "ls -X"),
    option("-Z, --context", "显示文件的安全上下文。", "ls -lZ"),
    option("-1", "每行只显示一个项目。", "ls -1"),
    option("--help", "显示帮助信息并退出。", "ls --help"),
    option("--version", "显示版本信息并退出。", "ls --version"),
  ],
  pwd: [
    option("-L, --logical", "显示包含符号链接的逻辑工作目录。", "pwd -L"),
    option("-P, --physical", "解析符号链接后显示物理工作目录。", "pwd -P"),
    option("--help", "显示帮助信息。", "pwd --help"),
    option("--version", "显示版本信息。", "pwd --version"),
  ],
  mkdir: [
    option("-m, --mode=MODE", "创建目录时直接设置权限模式。", "mkdir -m 750 app"),
    option("-p, --parents", "按需创建父目录，已存在时不报错。", "mkdir -p app/logs/archive"),
    option("-v, --verbose", "为每个创建的目录输出提示。", "mkdir -pv app/logs"),
    option("-Z", "将 SELinux 安全上下文设置为默认类型。", "mkdir -Z secure"),
    option("--context=CTX", "为新目录指定 SELinux 安全上下文。", "mkdir --context=system_u:object_r:tmp_t:s0 work"),
    option("--help", "显示帮助信息。", "mkdir --help"),
    option("--version", "显示版本信息。", "mkdir --version"),
  ],
  cp: [
    option("-a, --archive", "归档复制，尽量保留属性并递归复制。", "cp -a source/ backup/"),
    option("--attributes-only", "只复制文件属性，不复制数据。", "cp --attributes-only source target"),
    option("--backup[=CONTROL]", "覆盖目标前创建备份。", "cp --backup=numbered file target/"),
    option("-b", "类似 --backup，但不接受控制参数。", "cp -b file target/"),
    option("--copy-contents", "递归时复制特殊文件的内容。", "cp -R --copy-contents source target"),
    option("-d", "等同于 --no-dereference --preserve=links。", "cp -d link target/"),
    option("-f, --force", "无法打开目标文件时先删除再复制。", "cp -f config.new config"),
    option("-H", "跟随命令行参数中的符号链接。", "cp -HR source target"),
    option("-i, --interactive", "覆盖目标前询问确认。", "cp -i file target/"),
    option("-l, --link", "创建硬链接而不是复制文件。", "cp -l file hardlink"),
    option("-L, --dereference", "始终跟随源文件中的符号链接。", "cp -LR source target"),
    option("-n, --no-clobber", "不覆盖已经存在的目标文件。", "cp -n *.conf backup/"),
    option("-P, --no-dereference", "不跟随源文件中的符号链接。", "cp -PR source target"),
    option("-p", "保留模式、所有权和时间戳。", "cp -p file backup/"),
    option("--preserve[=ATTR_LIST]", "保留指定属性，如 mode、ownership、timestamps、links。", "cp --preserve=mode,timestamps file backup/"),
    option("--no-preserve=ATTR_LIST", "明确不保留指定属性。", "cp --no-preserve=ownership file backup/"),
    option("-R, -r, --recursive", "递归复制目录。", "cp -R source/ target/"),
    option("--reflink[=WHEN]", "控制写时复制，WHEN 为 auto、always 或 never。", "cp --reflink=auto image.img clone.img"),
    option("--remove-destination", "复制前删除已存在的目标文件。", "cp --remove-destination file target"),
    option("--sparse=WHEN", "控制稀疏文件创建方式。", "cp --sparse=always disk.img backup.img"),
    option("-s, --symbolic-link", "创建符号链接而不是复制。", "cp -s file link"),
    option("-t, --target-directory=DIR", "将所有源文件复制到指定目录。", "cp -t backup file1 file2"),
    option("-T, --no-target-directory", "将目标参数始终视为普通路径。", "cp -T source target"),
    option("-u, --update", "仅当源文件更新或目标不存在时复制。", "cp -u *.conf backup/"),
    option("-v, --verbose", "显示正在执行的复制操作。", "cp -v file backup/"),
    option("-x, --one-file-system", "递归时不跨越文件系统。", "cp -ax /data /backup/"),
    option("--help", "显示帮助信息。", "cp --help"),
    option("--version", "显示版本信息。", "cp --version"),
  ],
  mv: [
    option("--backup[=CONTROL]", "覆盖目标前创建备份。", "mv --backup=numbered old new"),
    option("-b", "覆盖前创建备份。", "mv -b config.new config"),
    option("-f, --force", "覆盖前不询问。", "mv -f old new"),
    option("-i, --interactive", "覆盖目标前询问确认。", "mv -i old new"),
    option("-n, --no-clobber", "不覆盖已存在的目标。", "mv -n file target/"),
    option("--strip-trailing-slashes", "移除源参数末尾的斜杠。", "mv --strip-trailing-slashes source/ target"),
    option("-t, --target-directory=DIR", "把所有源移动到指定目录。", "mv -t archive file1 file2"),
    option("-T, --no-target-directory", "把目标始终视为普通路径。", "mv -T source target"),
    option("-u, --update", "仅当源更新或目标不存在时移动。", "mv -u file target/"),
    option("-v, --verbose", "显示每次移动操作。", "mv -v old new"),
    option("--help", "显示帮助信息。", "mv --help"),
    option("--version", "显示版本信息。", "mv --version"),
  ],
  rm: [
    option("-f, --force", "忽略不存在的文件且不询问。", "rm -f app.tmp"),
    option("-i", "删除每个文件前都询问。", "rm -i file"),
    option("-I", "删除多个文件或递归删除前询问一次。", "rm -I *.log"),
    option("--interactive=WHEN", "设置询问策略：never、once 或 always。", "rm --interactive=once *.tmp"),
    option("--one-file-system", "递归时跳过其他文件系统。", "rm -rf --one-file-system old-root"),
    option("--no-preserve-root", "允许递归处理根目录；风险极高。", "rm --no-preserve-root --help"),
    option("--preserve-root[=all]", "拒绝递归删除根目录或不同设备上的根。", "rm --preserve-root=all -r target"),
    option("-r, -R, --recursive", "递归删除目录及其内容。", "rm -r old-directory"),
    option("-d, --dir", "删除空目录。", "rm -d empty-directory"),
    option("-v, --verbose", "显示正在删除的文件。", "rm -v file"),
    option("--help", "显示帮助信息。", "rm --help"),
    option("--version", "显示版本信息。", "rm --version"),
  ],
  touch: [
    option("-a", "只更新访问时间。", "touch -a file"),
    option("-c, --no-create", "文件不存在时不创建。", "touch -c file"),
    option("-d, --date=STRING", "使用可读日期字符串设置时间。", "touch -d '2026-08-12 10:00' file"),
    option("-f", "兼容选项，不执行额外操作。", "touch -f file"),
    option("-h, --no-dereference", "修改符号链接本身而不是目标。", "touch -h link"),
    option("-m", "只更新修改时间。", "touch -m file"),
    option("-r, --reference=FILE", "使用参考文件的时间戳。", "touch -r source target"),
    option("-t STAMP", "按 [[CC]YY]MMDDhhmm[.ss] 设置时间。", "touch -t 202608121030.00 file"),
    option("--time=WORD", "指定修改 access、atime、modify 或 mtime。", "touch --time=mtime file"),
    option("--help", "显示帮助信息。", "touch --help"),
    option("--version", "显示版本信息。", "touch --version"),
  ],
  cat: [
    option("-A, --show-all", "等同于 -vET，显示不可见字符和行尾。", "cat -A file"),
    option("-b, --number-nonblank", "为非空行编号，会覆盖 -n。", "cat -b file"),
    option("-e", "等同于 -vE。", "cat -e file"),
    option("-E, --show-ends", "在每行末尾显示 $。", "cat -E file"),
    option("-n, --number", "为所有输出行编号。", "cat -n file"),
    option("-s, --squeeze-blank", "将连续空行压缩成一行。", "cat -s file"),
    option("-t", "等同于 -vT。", "cat -t file"),
    option("-T, --show-tabs", "将制表符显示为 ^I。", "cat -T file"),
    option("-u", "兼容选项，不执行额外操作。", "cat -u file"),
    option("-v, --show-nonprinting", "用 ^ 和 M- 记法显示不可打印字符。", "cat -v file"),
    option("--help", "显示帮助信息。", "cat --help"),
    option("--version", "显示版本信息。", "cat --version"),
  ],
  head: [
    option("-c, --bytes=[-]NUM", "输出前 NUM 字节；带负号时排除末尾 NUM 字节。", "head -c 100 file"),
    option("-n, --lines=[-]NUM", "输出前 NUM 行；带负号时排除末尾 NUM 行。", "head -n 20 file"),
    option("-q, --quiet, --silent", "处理多个文件时不显示文件名标题。", "head -q file1 file2"),
    option("-v, --verbose", "始终显示文件名标题。", "head -v file"),
    option("-z, --zero-terminated", "使用 NUL 而不是换行符分隔记录。", "head -z -n 10 data"),
    option("--help", "显示帮助信息。", "head --help"),
    option("--version", "显示版本信息。", "head --version"),
  ],
  tail: [
    option("-c, --bytes=[+]NUM", "输出末尾 NUM 字节；+NUM 表示从第 NUM 字节开始。", "tail -c 1K file"),
    option("-f, --follow[=NAME|DESCRIPTOR]", "持续输出文件追加的内容。", "tail -f app.log"),
    option("-F", "等同于 --follow=name --retry，适合日志轮转。", "tail -F app.log"),
    option("-n, --lines=[+]NUM", "输出末尾 NUM 行；+NUM 表示从第 NUM 行开始。", "tail -n 200 app.log"),
    option("--max-unchanged-stats=N", "按名称跟踪时，N 次无变化后重新打开文件。", "tail --follow=name --max-unchanged-stats=5 app.log"),
    option("--pid=PID", "指定进程结束后停止跟踪。", "tail -f --pid=1234 app.log"),
    option("-q, --quiet, --silent", "处理多个文件时不显示标题。", "tail -q file1 file2"),
    option("--retry", "文件暂时不可访问时继续重试。", "tail --retry -f app.log"),
    option("-s, --sleep-interval=N", "跟踪时每 N 秒检查一次。", "tail -f -s 0.5 app.log"),
    option("-v, --verbose", "始终显示文件名标题。", "tail -v app.log"),
    option("-z, --zero-terminated", "使用 NUL 而不是换行符分隔记录。", "tail -z -n 10 data"),
    option("--help", "显示帮助信息。", "tail --help"),
    option("--version", "显示版本信息。", "tail --version"),
  ],
  grep: [
    option("-E, --extended-regexp", "使用扩展正则表达式。", "grep -E 'error|warn' app.log"),
    option("-F, --fixed-strings", "把模式当作固定字符串而不是正则表达式。", "grep -F 'a.b' file"),
    option("-G, --basic-regexp", "使用基本正则表达式，默认模式。", "grep -G '^root:' /etc/passwd"),
    option("-P, --perl-regexp", "使用 Perl 兼容正则表达式。", "grep -P '\\d{4}-\\d{2}-\\d{2}' file"),
    option("-e, --regexp=PATTERN", "指定一个搜索模式，可重复使用。", "grep -e error -e warning app.log"),
    option("-f, --file=FILE", "从文件读取搜索模式。", "grep -f patterns.txt app.log"),
    option("-i, --ignore-case", "忽略大小写。", "grep -i error app.log"),
    option("--no-ignore-case", "区分大小写。", "grep --no-ignore-case Error app.log"),
    option("-w, --word-regexp", "只匹配完整单词。", "grep -w root /etc/passwd"),
    option("-x, --line-regexp", "只匹配整行。", "grep -x 'READY' status.txt"),
    option("-z, --null-data", "使用 NUL 而不是换行符分隔记录。", "grep -z pattern data"),
    option("-s, --no-messages", "不显示文件读取错误。", "grep -s pattern missing.file"),
    option("-v, --invert-match", "输出不匹配模式的行。", "grep -v '^#' config"),
    option("-V, --version", "显示版本信息。", "grep --version"),
    option("--help", "显示帮助信息。", "grep --help"),
    option("-m, --max-count=NUM", "匹配 NUM 行后停止读取文件。", "grep -m 10 error app.log"),
    option("-b, --byte-offset", "在结果前显示字节偏移量。", "grep -b error app.log"),
    option("-n, --line-number", "在结果前显示行号。", "grep -n error app.log"),
    option("--line-buffered", "每输出一行立即刷新缓冲区。", "tail -f app.log | grep --line-buffered error"),
    option("-H, --with-filename", "每条结果都显示文件名。", "grep -H error *.log"),
    option("-h, --no-filename", "处理多个文件时隐藏文件名。", "grep -h error *.log"),
    option("--label=LABEL", "将标准输入显示为指定文件名。", "cat app.log | grep --label=stdin -H error"),
    option("-o, --only-matching", "只输出匹配到的部分。", "grep -oE '[0-9]+' file"),
    option("-q, --quiet, --silent", "不输出结果，只使用退出状态。", "grep -q error app.log"),
    option("--binary-files=TYPE", "指定二进制文件处理方式。", "grep --binary-files=text pattern binary.dat"),
    option("-a, --text", "把二进制文件当作文本。", "grep -a pattern binary.dat"),
    option("-I", "忽略二进制文件。", "grep -I pattern *"),
    option("-d, --directories=ACTION", "指定目录处理方式：read、recurse 或 skip。", "grep -d skip pattern *"),
    option("-D, --devices=ACTION", "指定设备、FIFO 等特殊文件的处理方式。", "grep -D skip pattern /dev/*"),
    option("-r, --recursive", "递归搜索目录。", "grep -r error /var/log"),
    option("-R, --dereference-recursive", "递归搜索并跟随符号链接。", "grep -R error project/"),
    option("--include=GLOB", "只搜索匹配模式的文件。", "grep -r --include='*.js' TODO src/"),
    option("--exclude=GLOB", "跳过匹配模式的文件。", "grep -r --exclude='*.min.js' TODO ."),
    option("--exclude-from=FILE", "从文件读取排除模式。", "grep -r --exclude-from=.grepignore TODO ."),
    option("--exclude-dir=GLOB", "跳过匹配模式的目录。", "grep -r --exclude-dir=node_modules TODO ."),
    option("-L, --files-without-match", "只输出不包含匹配内容的文件名。", "grep -L error *.log"),
    option("-l, --files-with-matches", "只输出包含匹配内容的文件名。", "grep -l error *.log"),
    option("-c, --count", "只输出每个文件的匹配行数。", "grep -c error app.log"),
    option("-T, --initial-tab", "字段分隔处使用制表符对齐。", "grep -nT error app.log"),
    option("-Z, --null", "文件名后输出 NUL 字符。", "grep -rlZ error ."),
    option("-B, --before-context=NUM", "显示匹配行之前 NUM 行。", "grep -B 3 error app.log"),
    option("-A, --after-context=NUM", "显示匹配行之后 NUM 行。", "grep -A 3 error app.log"),
    option("-C, --context=NUM", "显示匹配行前后各 NUM 行。", "grep -C 2 error app.log"),
    option("--color[=WHEN]", "高亮匹配内容。", "grep --color=auto error app.log"),
  ],
  find: [
    option("-H", "只跟随命令行参数中的符号链接。", "find -H link -name '*.log'"),
    option("-L", "跟随所有符号链接。", "find -L . -name '*.log'"),
    option("-P", "不跟随符号链接，默认行为。", "find -P . -name '*.log'"),
    option("-Olevel", "设置查询优化级别。", "find -O2 . -name '*.log'"),
    option("-D debugopts", "输出指定类型的调试信息。", "find -D tree . -name '*.log'"),
    option("-amin N", "按最后访问时间分钟数筛选。", "find . -amin -10"),
    option("-anewer FILE", "查找访问时间晚于参考文件的项目。", "find . -anewer marker"),
    option("-atime N", "按最后访问时间天数筛选。", "find . -atime +30"),
    option("-cmin N", "按状态变更时间分钟数筛选。", "find . -cmin -60"),
    option("-cnewer FILE", "查找状态变更时间晚于参考文件的项目。", "find . -cnewer marker"),
    option("-ctime N", "按状态变更时间天数筛选。", "find . -ctime -1"),
    option("-mmin N", "按修改时间分钟数筛选。", "find . -mmin -30"),
    option("-mtime N", "按修改时间天数筛选。", "find . -mtime +7"),
    option("-newer FILE", "查找修改时间晚于参考文件的项目。", "find . -newer marker"),
    option("-newermt DATE", "查找修改时间晚于指定日期的项目。", "find . -newermt '2026-08-01'"),
    option("-empty", "匹配空文件或空目录。", "find . -empty"),
    option("-executable", "匹配当前用户可执行的项目。", "find . -type f -executable"),
    option("-readable", "匹配当前用户可读的项目。", "find . -readable"),
    option("-writable", "匹配当前用户可写的项目。", "find . -writable"),
    option("-fstype TYPE", "匹配位于指定文件系统上的项目。", "find / -fstype ext4"),
    option("-gid N", "按数字组 ID 匹配。", "find . -gid 1000"),
    option("-group NAME", "按组名匹配。", "find . -group developers"),
    option("-uid N", "按数字用户 ID 匹配。", "find . -uid 1000"),
    option("-user NAME", "按所有者用户名匹配。", "find . -user app"),
    option("-name PATTERN", "按区分大小写的名称匹配。", "find . -name '*.log'"),
    option("-iname PATTERN", "按不区分大小写的名称匹配。", "find . -iname '*.jpg'"),
    option("-path PATTERN", "按完整路径匹配。", "find . -path '*/cache/*'"),
    option("-ipath PATTERN", "按不区分大小写的完整路径匹配。", "find . -ipath '*/CACHE/*'"),
    option("-regex PATTERN", "使用正则表达式匹配完整路径。", "find . -regex '.*\\.log'"),
    option("-iregex PATTERN", "使用不区分大小写的正则匹配完整路径。", "find . -iregex '.*\\.JPG'"),
    option("-lname PATTERN", "按符号链接目标匹配。", "find . -lname '*target*'"),
    option("-inum N", "按 inode 编号匹配。", "find . -inum 123456"),
    option("-links N", "按硬链接数量匹配。", "find . -links +1"),
    option("-perm MODE", "按权限位精确匹配。", "find . -perm 644"),
    option("-size N[cwbkMG]", "按文件大小匹配。", "find . -size +100M"),
    option("-type TYPE", "按类型匹配，如 f 文件、d 目录、l 链接。", "find . -type f"),
    option("-xtype TYPE", "按符号链接解析后的类型匹配。", "find -L . -xtype l"),
    option("-maxdepth N", "最多进入 N 层目录。", "find . -maxdepth 2 -type f"),
    option("-mindepth N", "至少进入 N 层后才匹配。", "find . -mindepth 1 -type d"),
    option("-mount, -xdev", "不进入其他文件系统。", "find / -xdev -name '*.log'"),
    option("-daystart", "时间测试从当天开始而不是过去 24 小时。", "find . -daystart -mtime 0"),
    option("-ignore_readdir_race", "忽略读取目录后文件消失导致的错误。", "find . -ignore_readdir_race -type f"),
    option("-noignore_readdir_race", "恢复报告目录读取竞争错误。", "find . -noignore_readdir_race"),
    option("-noleaf", "不使用目录硬链接数优化。", "find . -noleaf -type f"),
    option("-regextype TYPE", "指定正则表达式语法类型。", "find . -regextype posix-extended -regex '.*\\.(log|txt)'"),
    option("-warn, -nowarn", "启用或关闭警告信息。", "find . -nowarn -name '*.log'"),
    option("-delete", "删除匹配项目，会隐含 -depth。", "find . -type f -name '*.tmp' -delete"),
    option("-exec CMD {} ;", "为每个匹配项目执行命令。", "find . -name '*.log' -exec gzip {} \\;"),
    option("-exec CMD {} +", "批量把匹配项目传给命令。", "find . -name '*.log' -exec grep -l error {} +"),
    option("-execdir CMD {} ;", "在匹配文件所在目录执行命令。", "find . -name '*.tmp' -execdir rm -- {} \\;"),
    option("-ok CMD {} ;", "执行前逐次询问。", "find . -name '*.tmp' -ok rm {} \\;"),
    option("-print", "输出匹配路径，默认动作。", "find . -type f -print"),
    option("-print0", "用 NUL 分隔路径，适合配合 xargs -0。", "find . -type f -print0"),
    option("-printf FORMAT", "使用自定义格式输出。", "find . -type f -printf '%s %p\\n'"),
    option("-ls", "以类似 ls -dils 的格式输出。", "find . -type f -ls"),
    option("-prune", "阻止进入当前目录。", "find . -path './node_modules' -prune -o -type f -print"),
    option("-quit", "匹配后立即退出。", "find . -name config.yml -print -quit"),
    option("! EXPR, -not EXPR", "对表达式结果取反。", "find . -type f ! -name '*.log'"),
    option("EXPR -a EXPR, -and", "逻辑与。", "find . -type f -a -name '*.log'"),
    option("EXPR -o EXPR, -or", "逻辑或。", "find . -name '*.log' -o -name '*.txt'"),
    option("--help", "显示帮助信息。", "find --help"),
    option("--version", "显示版本信息。", "find --version"),
  ],
  chmod: [
    option("-c, --changes", "只在权限发生变化时输出信息。", "chmod -c 640 file"),
    option("-f, --silent, --quiet", "不显示大多数错误信息。", "chmod -f 640 file"),
    option("-v, --verbose", "为每个处理的文件输出诊断信息。", "chmod -v 640 file"),
    option("--no-preserve-root", "不特殊对待根目录。", "chmod --no-preserve-root --help"),
    option("--preserve-root", "拒绝递归操作根目录。", "chmod --preserve-root -R 755 target"),
    option("--reference=RFILE", "使用参考文件的权限模式。", "chmod --reference=source target"),
    option("-R, --recursive", "递归修改目录和文件权限。", "chmod -R 750 app/"),
    option("-H", "递归时跟随命令行参数中的目录符号链接。", "chmod -RH 750 link"),
    option("-L", "递归时跟随所有目录符号链接。", "chmod -RL 750 tree/"),
    option("-P", "递归时不跟随任何符号链接，默认行为。", "chmod -RP 750 tree/"),
    option("--help", "显示帮助信息。", "chmod --help"),
    option("--version", "显示版本信息。", "chmod --version"),
  ],
  chown: [
    option("-c, --changes", "只在所有权发生变化时输出信息。", "chown -c app:app file"),
    option("-f, --silent, --quiet", "不显示大多数错误信息。", "chown -f app:app file"),
    option("-v, --verbose", "为每个处理的文件输出诊断信息。", "chown -v app:app file"),
    option("--dereference", "修改符号链接目标的所有权，默认行为。", "chown --dereference app:app link"),
    option("-h, --no-dereference", "修改符号链接本身的所有权。", "chown -h app:app link"),
    option("--from=CURRENT_OWNER:CURRENT_GROUP", "仅在当前所有权匹配时修改。", "chown --from=root:root app:app file"),
    option("--no-preserve-root", "不特殊对待根目录。", "chown --no-preserve-root --help"),
    option("--preserve-root", "拒绝递归操作根目录。", "chown --preserve-root -R app:app target"),
    option("--reference=RFILE", "使用参考文件的所有者和组。", "chown --reference=source target"),
    option("-R, --recursive", "递归修改目录和文件所有权。", "chown -R app:app app/"),
    option("-H", "递归时跟随命令行参数中的目录符号链接。", "chown -RH app:app link"),
    option("-L", "递归时跟随所有目录符号链接。", "chown -RL app:app tree/"),
    option("-P", "递归时不跟随符号链接。", "chown -RP app:app tree/"),
    option("--help", "显示帮助信息。", "chown --help"),
    option("--version", "显示版本信息。", "chown --version"),
  ],
  df: [
    option("-a, --all", "包含伪文件系统、重复文件系统和不可访问文件系统。", "df -a"),
    option("-B, --block-size=SIZE", "按指定单位显示容量。", "df -B 1M"),
    option("-h, --human-readable", "以 K、M、G 等易读单位显示。", "df -h"),
    option("-H, --si", "使用 1000 进制易读单位。", "df -H"),
    option("-i, --inodes", "显示 inode 使用量而不是块使用量。", "df -i"),
    option("-k", "使用 1024 字节块。", "df -k"),
    option("-l, --local", "只显示本地文件系统。", "df -hl"),
    option("--no-sync", "获取使用量前不执行 sync，默认行为。", "df --no-sync"),
    option("--output[=FIELD_LIST]", "只显示指定字段。", "df --output=source,fstype,size,used,avail,pcent,target"),
    option("-P, --portability", "使用 POSIX 输出格式。", "df -P"),
    option("--sync", "获取使用量前执行 sync。", "df --sync -h"),
    option("--total", "在末尾显示总计。", "df -h --total"),
    option("-t, --type=TYPE", "只显示指定类型的文件系统。", "df -t ext4 -h"),
    option("-T, --print-type", "显示文件系统类型。", "df -hT"),
    option("-x, --exclude-type=TYPE", "排除指定类型的文件系统。", "df -x tmpfs -h"),
    option("--help", "显示帮助信息。", "df --help"),
    option("--version", "显示版本信息。", "df --version"),
  ],
  du: [
    option("-0, --null", "每条输出以 NUL 结束。", "du -0 -a ."),
    option("-a, --all", "显示所有文件，而不只显示目录。", "du -ah ."),
    option("--apparent-size", "显示表观大小而不是磁盘占用。", "du -h --apparent-size file"),
    option("-B, --block-size=SIZE", "按指定单位显示大小。", "du -B 1M ."),
    option("-b, --bytes", "等同于 --apparent-size --block-size=1。", "du -b file"),
    option("-c, --total", "在末尾显示总计。", "du -ch *.log"),
    option("-D, --dereference-args", "跟随命令行参数中的符号链接。", "du -Dh link"),
    option("-d, --max-depth=N", "只显示不超过 N 层的目录汇总。", "du -h --max-depth=1 /var"),
    option("--files0-from=FILE", "从 NUL 分隔文件读取要统计的路径。", "du --files0-from=paths.bin"),
    option("-H", "等同于 --dereference-args。", "du -H link"),
    option("-h, --human-readable", "以易读单位显示大小。", "du -h ."),
    option("--inodes", "显示 inode 使用量。", "du --inodes ."),
    option("-k", "使用 1024 字节块。", "du -k ."),
    option("-L, --dereference", "跟随所有符号链接。", "du -Lh ."),
    option("-l, --count-links", "重复统计硬链接文件。", "du -lh --count-links ."),
    option("-m", "使用 1 MiB 块。", "du -m ."),
    option("-P, --no-dereference", "不跟随符号链接，默认行为。", "du -P ."),
    option("-S, --separate-dirs", "目录大小不包含子目录大小。", "du -hS ."),
    option("--si", "使用 1000 进制易读单位。", "du --si ."),
    option("-s, --summarize", "只显示每个参数的总计。", "du -sh *"),
    option("-t, --threshold=SIZE", "排除小于或大于阈值的项目。", "du -h -t 100M ."),
    option("--time", "显示目录或文件的最后修改时间。", "du -h --time ."),
    option("--time-style=STYLE", "指定时间显示格式。", "du --time --time-style=long-iso ."),
    option("-X, --exclude-from=FILE", "从文件读取排除模式。", "du -h -X .duignore ."),
    option("--exclude=PATTERN", "排除匹配模式的项目。", "du -h --exclude='*.log' ."),
    option("-x, --one-file-system", "跳过其他文件系统。", "du -hx /"),
    option("--help", "显示帮助信息。", "du --help"),
    option("--version", "显示版本信息。", "du --version"),
  ],
  tar: [
    option("-c, --create", "创建新归档。", "tar -cf archive.tar app/"),
    option("-x, --extract, --get", "从归档中提取文件。", "tar -xf archive.tar"),
    option("-t, --list", "列出归档内容。", "tar -tf archive.tar"),
    option("-r, --append", "向归档末尾追加文件。", "tar -rf archive.tar new.txt"),
    option("-u, --update", "只追加比归档中副本更新的文件。", "tar -uf archive.tar app/"),
    option("-A, --catenate, --concatenate", "把一个归档追加到另一个归档。", "tar -Af main.tar extra.tar"),
    option("--delete", "从归档中删除成员。", "tar --delete -f archive.tar old.txt"),
    option("-f, --file=ARCHIVE", "指定归档文件名。", "tar -cf backup.tar data/"),
    option("-C, --directory=DIR", "执行后续操作前切换目录。", "tar -C /srv -czf app.tar.gz app"),
    option("-v, --verbose", "详细显示处理的文件。", "tar -cvf archive.tar app/"),
    option("-z, --gzip", "通过 gzip 压缩或解压。", "tar -czf archive.tar.gz app/"),
    option("-j, --bzip2", "通过 bzip2 压缩或解压。", "tar -cjf archive.tar.bz2 app/"),
    option("-J, --xz", "通过 xz 压缩或解压。", "tar -cJf archive.tar.xz app/"),
    option("--zstd", "通过 zstd 压缩或解压。", "tar --zstd -cf archive.tar.zst app/"),
    option("-a, --auto-compress", "根据归档后缀自动选择压缩程序。", "tar -caf archive.tar.xz app/"),
    option("--exclude=PATTERN", "排除匹配模式的文件。", "tar -czf app.tar.gz --exclude='*.log' app/"),
    option("-X, --exclude-from=FILE", "从文件读取排除模式。", "tar -czf app.tar.gz -X exclude.txt app/"),
    option("--strip-components=N", "提取时移除路径开头 N 层。", "tar -xf archive.tar --strip-components=1"),
    option("-p, --preserve-permissions", "提取时保留文件权限。", "tar -xpf archive.tar"),
    option("--same-owner", "提取时保留归档中的所有者。", "sudo tar --same-owner -xf backup.tar"),
    option("--no-same-owner", "提取时归当前用户所有。", "tar --no-same-owner -xf archive.tar"),
    option("-k, --keep-old-files", "不覆盖已存在的文件。", "tar -xkf archive.tar"),
    option("--keep-newer-files", "不覆盖比归档副本更新的文件。", "tar --keep-newer-files -xf archive.tar"),
    option("--overwrite", "提取时覆盖已存在文件。", "tar --overwrite -xf archive.tar"),
    option("--remove-files", "成功加入归档后删除源文件。", "tar --remove-files -cf logs.tar *.log"),
    option("--checkpoint=N", "每处理 N 条记录执行检查点动作。", "tar -cf archive.tar --checkpoint=100 app/"),
    option("--checkpoint-action=ACTION", "在检查点执行指定动作。", "tar -cf archive.tar --checkpoint=100 --checkpoint-action=dot app/"),
    option("--warning=KEYWORD", "控制指定类别的警告。", "tar --warning=no-file-changed -czf app.tar.gz app/"),
    option("--help", "显示帮助信息。", "tar --help"),
    option("--version", "显示版本信息。", "tar --version"),
  ],
  ssh: [
    option("-4", "强制只使用 IPv4。", "ssh -4 user@host"),
    option("-6", "强制只使用 IPv6。", "ssh -6 user@host"),
    option("-A", "启用 SSH Agent 转发。", "ssh -A user@host"),
    option("-a", "禁用 SSH Agent 转发。", "ssh -a user@host"),
    option("-C", "启用压缩。", "ssh -C user@host"),
    option("-c CIPHER_SPEC", "指定会话加密算法。", "ssh -c aes256-gcm@openssh.com user@host"),
    option("-D [bind_address:]port", "建立动态 SOCKS 代理。", "ssh -D 1080 user@host"),
    option("-E LOG_FILE", "将调试日志写入文件。", "ssh -E ssh-debug.log -vv user@host"),
    option("-e ESCAPE_CHAR", "设置转义字符。", "ssh -e '~' user@host"),
    option("-F CONFIGFILE", "指定用户配置文件。", "ssh -F ~/.ssh/work_config server"),
    option("-f", "认证后转入后台。", "ssh -f -N -L 8080:localhost:80 user@host"),
    option("-G", "打印计算后的主机配置并退出。", "ssh -G server"),
    option("-g", "允许远程主机连接本地转发端口。", "ssh -g -L 8080:localhost:80 user@host"),
    option("-I PKCS11", "指定 PKCS#11 共享库。", "ssh -I /usr/lib/pkcs11.so user@host"),
    option("-i IDENTITY_FILE", "指定私钥文件。", "ssh -i ~/.ssh/id_ed25519 user@host"),
    option("-J DESTINATION", "通过跳板机连接。", "ssh -J jump@bastion user@target"),
    option("-K", "启用 GSSAPI 凭据转发。", "ssh -K user@host"),
    option("-k", "禁用 GSSAPI 凭据转发。", "ssh -k user@host"),
    option("-L [bind_address:]port:host:hostport", "建立本地端口转发。", "ssh -L 3307:db.internal:3306 user@gateway"),
    option("-l LOGIN_NAME", "指定远程登录用户名。", "ssh -l root host"),
    option("-M", "将客户端设为连接共享主进程。", "ssh -M -S ~/.ssh/control-%r@%h:%p user@host"),
    option("-m MAC_SPEC", "指定 MAC 算法。", "ssh -m hmac-sha2-256 user@host"),
    option("-N", "不执行远程命令，适合端口转发。", "ssh -N -L 8080:localhost:80 user@host"),
    option("-n", "将标准输入重定向自 /dev/null。", "ssh -n user@host uptime"),
    option("-O CTL_CMD", "控制连接共享主进程。", "ssh -O check -S ~/.ssh/control user@host"),
    option("-o OPTION", "以配置文件格式指定一个选项。", "ssh -o ConnectTimeout=10 user@host"),
    option("-p PORT", "指定远程 SSH 端口。", "ssh -p 2222 user@host"),
    option("-Q QUERY_OPTION", "查询支持的算法。", "ssh -Q cipher"),
    option("-q", "安静模式，抑制警告和诊断信息。", "ssh -q user@host"),
    option("-R [bind_address:]port:host:hostport", "建立远程端口转发。", "ssh -R 8080:localhost:80 user@host"),
    option("-S CTL_PATH", "指定连接共享控制套接字。", "ssh -S ~/.ssh/control user@host"),
    option("-s", "请求远程子系统。", "ssh -s user@host sftp"),
    option("-T", "禁止分配伪终端。", "ssh -T git@github.com"),
    option("-t", "强制分配伪终端。", "ssh -t user@host sudo systemctl restart nginx"),
    option("-V", "显示版本信息。", "ssh -V"),
    option("-v, -vv, -vvv", "增加调试输出级别。", "ssh -vvv user@host"),
    option("-W host:port", "把标准输入输出转发到指定主机端口。", "ssh -W target:22 jump@bastion"),
    option("-w local_tun[:remote_tun]", "请求 tun 设备转发。", "ssh -w 0:0 user@host"),
    option("-X", "启用不受信任的 X11 转发。", "ssh -X user@host"),
    option("-x", "禁用 X11 转发。", "ssh -x user@host"),
    option("-Y", "启用受信任的 X11 转发。", "ssh -Y user@host"),
    option("-y", "通过 syslog 发送日志。", "ssh -y user@host"),
  ],
};

const add = (name, rows) => {
  commandOptions[name] = rows.map(([nameValue, description, example]) => option(nameValue, description, example));
};

Object.assign(commandOptions, extraCommandOptions, systemCommandOptions, toolCommandOptions);

// Shell、文本处理与用户管理命令。资料随应用离线提供。
add("cd", [
  ["DIR", "切换到指定目录。", "cd /var/log"], ["-", "切换到上一次所在目录。", "cd -"],
  ["~ 或不带参数", "切换到当前用户主目录。", "cd ~"], ["-L", "按逻辑路径处理符号链接，默认行为。", "cd -L ../app"],
  ["-P", "解析符号链接后进入物理路径。", "cd -P /srv/current"], ["-e", "配合 -P，无法确定物理路径时返回失败。", "cd -Pe /srv/current"],
]);
add("stat", [
  ["-L, --dereference", "跟随符号链接并显示目标信息。", "stat -L link"], ["-f, --file-system", "显示所在文件系统信息。", "stat -f file"],
  ["-c, --format=FORMAT", "按指定格式输出。", "stat -c '%n %s %U %a' file"], ["--printf=FORMAT", "按格式输出且不自动追加换行。", "stat --printf='%n %s\\n' file"],
  ["-t, --terse", "使用简洁格式输出。", "stat -t file"], ["--cached=MODE", "控制是否使用缓存属性。", "stat --cached=never file"],
  ["--help", "显示帮助信息。", "stat --help"], ["--version", "显示版本信息。", "stat --version"],
]);
add("less", [
  ["-N, --LINE-NUMBERS", "显示行号。", "less -N app.log"], ["-S, --chop-long-lines", "截断长行而不自动换行。", "less -S app.log"],
  ["-i, --ignore-case", "搜索时忽略大小写，除非模式包含大写字母。", "less -i app.log"], ["-I, --IGNORE-CASE", "搜索时始终忽略大小写。", "less -I app.log"],
  ["-R, --RAW-CONTROL-CHARS", "显示 ANSI 颜色控制序列。", "less -R color.log"], ["-F, --quit-if-one-screen", "内容不足一屏时自动退出。", "less -F file"],
  ["-X, --no-init", "退出时保留终端内容。", "less -X file"], ["-f, --force", "强制打开非普通文件。", "less -f file"],
  ["-g", "只高亮最后一次搜索匹配。", "less -g file"], ["-G", "不高亮搜索匹配。", "less -G file"],
  ["-p PATTERN", "打开后跳到第一个匹配。", "less -p ERROR app.log"], ["-j N", "将目标行定位到屏幕第 N 行。", "less -j 5 app.log"],
  ["+G", "打开后直接跳到文件末尾。", "less +G app.log"], ["+F", "持续跟踪文件增长。", "less +F app.log"],
  ["--help", "显示 less 内置帮助。", "less --help"], ["--version", "显示版本信息。", "less --version"],
]);
add("sed", [
  ["-n, --quiet, --silent", "不自动输出模式空间。", "sed -n '1,20p' file"], ["--debug", "输出程序执行过程。", "sed --debug 's/a/b/' file"],
  ["-e SCRIPT, --expression=SCRIPT", "添加一段处理脚本。", "sed -e 's/foo/bar/g' file"], ["-f FILE, --file=FILE", "从文件读取处理脚本。", "sed -f rules.sed input"],
  ["--follow-symlinks", "原地编辑时跟随符号链接。", "sed -i --follow-symlinks 's/a/b/' link"], ["-i[SUFFIX], --in-place[=SUFFIX]", "原地编辑并可创建备份。", "sed -i.bak 's/old/new/g' config"],
  ["-l N, --line-length=N", "设置 l 命令的换行长度。", "sed -l 120 -n 'l' file"], ["--posix", "禁用 GNU 扩展。", "sed --posix -n '1p' file"],
  ["-E, -r, --regexp-extended", "使用扩展正则表达式。", "sed -E 's/(foo)+/bar/' file"], ["-s, --separate", "将每个输入文件视为独立数据流。", "sed -s -n '1p' *.log"],
  ["-u, --unbuffered", "尽量减少输出缓冲。", "tail -f app.log | sed -u 's/error/ERROR/'"], ["-z, --null-data", "使用 NUL 分隔记录。", "sed -z 's/a/b/g' data"],
  ["--help", "显示帮助信息。", "sed --help"], ["--version", "显示版本信息。", "sed --version"],
]);
add("awk", [
  ["-F SEP", "设置输入字段分隔符。", "awk -F: '{print $1}' /etc/passwd"], ["-f FILE", "从文件读取 awk 程序。", "awk -f report.awk data.txt"],
  ["-v VAR=VALUE", "在程序运行前设置变量。", "awk -v limit=10 '$1 > limit' data"], ["-e PROGRAM", "指定程序文本。", "awk -e '{print NF}' file"],
  ["-b, --characters-as-bytes", "按字节而不是字符处理。", "awk -b '{print length($0)}' file"], ["-c, --traditional", "使用传统 awk 行为。", "awk -c '{print $1}' file"],
  ["-C, --copyright", "显示版权信息。", "awk --copyright"], ["-d[FILE], --dump-variables[=FILE]", "将全局变量写入文件。", "awk --dump-variables=vars.txt '{sum+=$1}' data"],
  ["-D[FILE], --debug[=FILE]", "启用调试器。", "awk --debug program.awk data"], ["-g, --gen-pot", "扫描程序并生成翻译模板。", "awk --gen-pot -f program.awk"],
  ["-L VALUE, --lint=VALUE", "启用语法兼容性检查。", "awk --lint=fatal '{print $1}' file"], ["-M, --bignum", "启用任意精度算术。", "awk -M 'BEGIN{print 2^100}'"],
  ["-O, --optimize", "启用程序优化。", "awk -O -f report.awk data"], ["-p[FILE], --profile[=FILE]", "生成执行分析报告。", "awk --profile=awkprof.out -f report.awk data"],
  ["-P, --posix", "启用严格 POSIX 模式。", "awk --posix '{print $1}' file"], ["-S, --sandbox", "禁用 system、重定向等不安全能力。", "awk --sandbox '{print $1}' file"],
  ["--help", "显示帮助信息。", "awk --help"], ["--version", "显示版本信息。", "awk --version"],
]);
add("sort", [
  ["-b, --ignore-leading-blanks", "忽略字段前导空白。", "sort -b file"], ["-d, --dictionary-order", "只比较空白和字母数字字符。", "sort -d file"],
  ["-f, --ignore-case", "比较时忽略大小写。", "sort -f names.txt"], ["-g, --general-numeric-sort", "按通用数值排序。", "sort -g values.txt"],
  ["-h, --human-numeric-sort", "识别 K、M、G 等单位排序。", "sort -h sizes.txt"], ["-i, --ignore-nonprinting", "忽略不可打印字符。", "sort -i file"],
  ["-M, --month-sort", "按月份名称排序。", "sort -M months.txt"], ["-n, --numeric-sort", "按数值排序。", "sort -n numbers.txt"],
  ["-R, --random-sort", "随机排列。", "sort -R file"], ["--random-source=FILE", "指定随机数据来源。", "sort -R --random-source=/dev/urandom file"],
  ["-r, --reverse", "反向排序。", "sort -r file"], ["--sort=WORD", "指定排序类型。", "sort --sort=version versions.txt"],
  ["-V, --version-sort", "按版本号自然排序。", "sort -V versions.txt"], ["-c, --check", "检查文件是否已排序。", "sort -c file"],
  ["-C, --check=quiet", "静默检查是否已排序。", "sort -C file"], ["-k, --key=KEYDEF", "按指定字段排序。", "sort -t, -k2,2n data.csv"],
  ["-m, --merge", "合并已经排序的文件。", "sort -m part1 part2"], ["-o, --output=FILE", "将结果写入文件。", "sort -o sorted.txt file"],
  ["-s, --stable", "保持相同键记录的原始顺序。", "sort -s -k1,1 file"], ["-S, --buffer-size=SIZE", "设置内存缓冲区大小。", "sort -S 1G large.txt"],
  ["-t, --field-separator=SEP", "设置字段分隔符。", "sort -t: -k3,3n /etc/passwd"], ["-T, --temporary-directory=DIR", "设置临时目录。", "sort -T /data/tmp large.txt"],
  ["-u, --unique", "只保留相同排序键的一条记录。", "sort -u file"], ["-z, --zero-terminated", "使用 NUL 分隔记录。", "sort -z data"],
  ["--parallel=N", "最多使用 N 个并行排序线程。", "sort --parallel=4 large.txt"], ["--help", "显示帮助信息。", "sort --help"], ["--version", "显示版本信息。", "sort --version"],
]);
add("uniq", [
  ["-c, --count", "在每行前显示出现次数。", "sort file | uniq -c"], ["-d, --repeated", "只输出重复行。", "sort file | uniq -d"],
  ["-D, --all-repeated[=METHOD]", "输出所有重复行。", "sort file | uniq -D"], ["-f, --skip-fields=N", "比较时跳过前 N 个字段。", "uniq -f 1 file"],
  ["--group[=METHOD]", "按组显示重复内容。", "sort file | uniq --group=separate"], ["-i, --ignore-case", "比较时忽略大小写。", "sort -f file | uniq -i"],
  ["-s, --skip-chars=N", "比较时跳过前 N 个字符。", "uniq -s 4 file"], ["-u, --unique", "只输出没有重复的行。", "sort file | uniq -u"],
  ["-w, --check-chars=N", "每行最多比较 N 个字符。", "uniq -w 8 file"], ["-z, --zero-terminated", "使用 NUL 分隔记录。", "uniq -z data"],
  ["--help", "显示帮助信息。", "uniq --help"], ["--version", "显示版本信息。", "uniq --version"],
]);
add("wc", [
  ["-c, --bytes", "显示字节数。", "wc -c file"], ["-m, --chars", "显示字符数。", "wc -m file"],
  ["-l, --lines", "显示行数。", "wc -l file"], ["--files0-from=FILE", "从 NUL 分隔文件读取路径。", "wc -l --files0-from=paths.bin"],
  ["-L, --max-line-length", "显示最长行的显示宽度。", "wc -L file"], ["-w, --words", "显示单词数。", "wc -w file"],
  ["--help", "显示帮助信息。", "wc --help"], ["--version", "显示版本信息。", "wc --version"],
]);
add("cut", [
  ["-b, --bytes=LIST", "按字节位置截取。", "cut -b 1-10 file"], ["-c, --characters=LIST", "按字符位置截取。", "cut -c 1-10 file"],
  ["-d, --delimiter=DELIM", "设置字段分隔符。", "cut -d: -f1 /etc/passwd"], ["-f, --fields=LIST", "输出指定字段。", "cut -d, -f1,3 data.csv"],
  ["--complement", "输出 LIST 未选择的部分。", "cut -d, -f2 --complement data.csv"], ["-s, --only-delimited", "不输出不含分隔符的行。", "cut -s -d: -f1 file"],
  ["--output-delimiter=STRING", "设置输出字段分隔符。", "cut -d: -f1,3 --output-delimiter=, /etc/passwd"], ["-z, --zero-terminated", "使用 NUL 分隔记录。", "cut -z -d: -f1 data"],
  ["--help", "显示帮助信息。", "cut --help"], ["--version", "显示版本信息。", "cut --version"],
]);
add("xargs", [
  ["-0, --null", "输入项目由 NUL 分隔。", "find . -print0 | xargs -0 rm"], ["-a, --arg-file=FILE", "从文件读取参数。", "xargs -a paths.txt rm"],
  ["-d, --delimiter=CHAR", "指定输入分隔符。", "printf 'a,b' | xargs -d, echo"], ["-E END", "设置逻辑 EOF 字符串。", "xargs -E STOP echo"],
  ["-I REPLACE", "用输入行替换命令中的占位符。", "printf '%s\\n' a b | xargs -I{} cp {} backup/"], ["-L, --max-lines=N", "每次命令最多使用 N 行输入。", "xargs -L 1 echo"],
  ["-n, --max-args=N", "每次命令最多使用 N 个参数。", "printf '%s\\n' 1 2 3 | xargs -n2 echo"], ["-P, --max-procs=N", "并行运行最多 N 个进程。", "xargs -P 4 -n1 gzip"],
  ["-p, --interactive", "执行每条命令前询问。", "xargs -p rm"], ["-r, --no-run-if-empty", "没有输入时不运行命令。", "xargs -r echo"],
  ["-s, --max-chars=N", "限制每条命令行字符数。", "xargs -s 4096 echo"], ["-t, --verbose", "执行前将命令打印到标准错误。", "xargs -t rm"],
  ["-x, --exit", "超出大小限制时退出而不拆分。", "xargs -x -s 100 echo"], ["--show-limits", "显示命令行长度限制。", "xargs --show-limits"],
  ["--help", "显示帮助信息。", "xargs --help"], ["--version", "显示版本信息。", "xargs --version"],
]);
